blank_issues_enabled: true
contact_links:
  - name: Looking for documentation?
    url: https://ada-url.github.io/ada
    about: Please file an issue in our help repo.
  - name: 🌐 Found a problem with nodejs.org beyond the API reference docs?
    url: https://github.com/nodejs/nodejs.org/issues/new/choose
    about: Please file an issue in the Node.js website repo.
