name: Ubuntu 22.04

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'docs/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        shared: [ON, OFF]
        cxx: [g++-12, clang++-14]
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Build Rust crate
        run: |
          cd ./benchmarks/competitors/servo-url
          cargo build --release
      - name: Setup Ninja
        run: sudo apt-get install ninja-build
      - name: Prepare
        run: cmake -D ADA_BENCHMARKS=ON \
          -DBUILD_SHARED_LIBS=${{matrix.shared}} \
          -DSERVO_URL_LIB_DIR="$PWD/benchmarks/competitors/servo-url/target/release" \
          -G Ninja -B build
        env:
          CXX: ${{matrix.cxx}}
      - name: Build
        run: cmake --build build -j=2 --verbose
      - name: Test
        run: ctest --output-on-failure --test-dir build
      - name: Run default benchmark
        run: cd build && benchmarks/bench
